Check unbound var issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,7 +30,7 @@ jobs:
         command: mkdir -p .buildcache && echo "*" > .buildcache/.gitignore
         name: Ignore .buildcache
     - restore_cache:
-        key: package-20314f565b3b70b251508557ecc86f6dc12398cb-{{checksum ".buildcache/cache-keys/package-20314f565b3b70b251508557ecc86f6dc12398cb"}}
+        key: package-3bbe07883d71c2981f5dbe42e96005712b5a0c9a-{{checksum ".buildcache/cache-keys/package-3bbe07883d71c2981f5dbe42e96005712b5a0c9a"}}
         name: Restore package cache
     - run:
         command: make package-meta-all
@@ -42,20 +42,20 @@ jobs:
         command: ls -lahR .buildcache
         name: List Build Cache
     - run:
-        command: cp packages*.lock/pkgs.yml lockfile-1eedaf3e6e44c491.yml
+        command: cp packages*.lock/pkgs.yml lockfile-c10311342fd7fcd2.yml
         name: Update Lockfile Name
     - run:
-        command: tar -czf packages-1eedaf3e6e44c491.tar.gz .buildcache/packages lockfile-1eedaf3e6e44c491.yml
+        command: tar -czf packages-c10311342fd7fcd2.tar.gz .buildcache/packages lockfile-c10311342fd7fcd2.yml
         name: Create Raw Package Tarball
     - run:
-        command: tar -czf meta-1eedaf3e6e44c491.tar.gz .buildcache/packages/store/*.json lockfile-1eedaf3e6e44c491.yml
+        command: tar -czf meta-c10311342fd7fcd2.tar.gz .buildcache/packages/store/*.json lockfile-c10311342fd7fcd2.yml
         name: Create Metadata Tarball
     - store_artifacts:
-        path: lockfile-1eedaf3e6e44c491.yml
+        path: lockfile-c10311342fd7fcd2.yml
     - store_artifacts:
-        path: packages-1eedaf3e6e44c491.tar.gz
+        path: packages-c10311342fd7fcd2.tar.gz
     - store_artifacts:
-        path: meta-1eedaf3e6e44c491.tar.gz
+        path: meta-c10311342fd7fcd2.tar.gz
     - store_artifacts:
         path: .buildcache/packages
     environment:
@@ -197,6 +197,78 @@ jobs:
           npm install
           node scripts/index_search_content.js
         name: Push content to Algolia Index
+  linux_amd64_package:
+    docker:
+    - image: docker.mirror.hashicorp.services/circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - BUILDKIT_PROGRESS: plain
+    - PRODUCT_REVISION: ''
+    - PACKAGE_SPEC_ID: 3bbe07883d71c2981f5dbe42e96005712b5a0c9a
+    steps:
+    - setup_remote_docker:
+        docker_layer_caching: false
+        version: 19.03.12
+    - add_ssh_keys:
+        fingerprints:
+        - 0e:03:77:f4:e2:c3:56:c2:53:6a:03:e1:31:91:2f:06
+    - checkout:
+        path: .
+    - run:
+        command: make -C packages*.lock write-package-cache-key
+        name: Write package cache key
+    - restore_cache:
+        key: package-3bbe07883d71c2981f5dbe42e96005712b5a0c9a-{{checksum ".buildcache/cache-keys/package-3bbe07883d71c2981f5dbe42e96005712b5a0c9a"}}
+        name: Restore package cache
+    - run:
+        command: |2
+
+          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+            echo "No package found, continuing with build."
+            exit 0
+          fi
+          echo "Package already cached, skipping build."
+          circleci-agent step halt
+        name: Check cache status
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        key: copy-source_6be6_{{checksum ".buildcache/cache-keys/copy-source-6be6bbcf469c2d26620194eeee87f0c4ba470bde"}}
+        keys:
+        - go-modules_74c0_{{checksum ".buildcache/cache-keys/go-modules-74c0c94188690e22d738cb1784f8feba7c3dc00d"}}
+        - ui_dfc9_{{checksum ".buildcache/cache-keys/ui-dfc937906b9b645655c44bc782ef13c64ebe8dbb"}}
+        - base_cc87_{{checksum ".buildcache/cache-keys/base-cc87158f920a83b1c241d68474eed6734b32c511"}}
+        name: 'Restore Builder Image Cache: copy-source'
+    - run:
+        command: make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: |2-
+
+          KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
+          eval "$(ssh-agent -s)"
+          if [ -f "$KEYFILE" ]; then
+            ssh-add "$KEYFILE"
+          else
+            echo "==> INFO: SSH key for github.com not found"
+            echo "    Attempts to access private repositories from within"
+            echo "    the build will fail, e.g. for private go modules, or"
+            echo "    attempts to directly clone private repositories."
+          fi
+
+          make -C packages*.lock package
+        name: Compile Package
+    - run:
+        command: ls -lahR .buildcache/packages
+        name: List packages
+    - save_cache:
+        key: package-3bbe07883d71c2981f5dbe42e96005712b5a0c9a-{{checksum ".buildcache/cache-keys/package-3bbe07883d71c2981f5dbe42e96005712b5a0c9a"}}
+        name: Save package cache
+        paths:
+        - .buildcache/packages/store
   test-sql-12-alpine:
     machine:
       image: ubuntu-2004:202107-02
@@ -369,78 +441,6 @@ jobs:
         command: |
           ./scripts/trigger-merge-to-ent
         name: Trigger Merge to Enterprise
-  windows_amd64_package:
-    docker:
-    - image: docker.mirror.hashicorp.services/circleci/buildpack-deps
-    shell: /usr/bin/env bash -euo pipefail -c
-    environment:
-    - AUTO_INSTALL_TOOLS: 'YES'
-    - BUILDKIT_PROGRESS: plain
-    - PRODUCT_REVISION: ''
-    - PACKAGE_SPEC_ID: 20314f565b3b70b251508557ecc86f6dc12398cb
-    steps:
-    - setup_remote_docker:
-        docker_layer_caching: false
-        version: 19.03.12
-    - add_ssh_keys:
-        fingerprints:
-        - 0e:03:77:f4:e2:c3:56:c2:53:6a:03:e1:31:91:2f:06
-    - checkout:
-        path: .
-    - run:
-        command: make -C packages*.lock write-package-cache-key
-        name: Write package cache key
-    - restore_cache:
-        key: package-20314f565b3b70b251508557ecc86f6dc12398cb-{{checksum ".buildcache/cache-keys/package-20314f565b3b70b251508557ecc86f6dc12398cb"}}
-        name: Restore package cache
-    - run:
-        command: |2
-
-          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
-            echo "No package found, continuing with build."
-            exit 0
-          fi
-          echo "Package already cached, skipping build."
-          circleci-agent step halt
-        name: Check cache status
-    - run:
-        command: make -C packages*.lock write-builder-cache-keys
-        name: Write builder layer cache keys
-    - restore_cache:
-        key: copy-source_6be6_{{checksum ".buildcache/cache-keys/copy-source-6be6bbcf469c2d26620194eeee87f0c4ba470bde"}}
-        keys:
-        - go-modules_74c0_{{checksum ".buildcache/cache-keys/go-modules-74c0c94188690e22d738cb1784f8feba7c3dc00d"}}
-        - ui_dfc9_{{checksum ".buildcache/cache-keys/ui-dfc937906b9b645655c44bc782ef13c64ebe8dbb"}}
-        - base_cc87_{{checksum ".buildcache/cache-keys/base-cc87158f920a83b1c241d68474eed6734b32c511"}}
-        name: 'Restore Builder Image Cache: copy-source'
-    - run:
-        command: make -C packages*.lock load-builder-cache
-        name: Load whatever builder cache we have (if any) into the Docker daemon
-        no_output_timeout: 30m
-    - run:
-        command: |2-
-
-          KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
-          eval "$(ssh-agent -s)"
-          if [ -f "$KEYFILE" ]; then
-            ssh-add "$KEYFILE"
-          else
-            echo "==> INFO: SSH key for github.com not found"
-            echo "    Attempts to access private repositories from within"
-            echo "    the build will fail, e.g. for private go modules, or"
-            echo "    attempts to directly clone private repositories."
-          fi
-
-          make -C packages*.lock package
-        name: Compile Package
-    - run:
-        command: ls -lahR .buildcache/packages
-        name: List packages
-    - save_cache:
-        key: package-20314f565b3b70b251508557ecc86f6dc12398cb-{{checksum ".buildcache/cache-keys/package-20314f565b3b70b251508557ecc86f6dc12398cb"}}
-        name: Save package cache
-        paths:
-        - .buildcache/packages/store
   test-sql-latest:
     machine:
       image: ubuntu-2004:202107-02
@@ -453,15 +453,15 @@ jobs:
           make test-sql POSTGRES_DOCKER_IMAGE_BASE=docker.mirror.hashicorp.services/postgres PG_DOCKER_TAG=latest
         name: Run SQL PgTap Tests
 workflows:
-  build-1eedaf3e6e44c491:
+  build-c10311342fd7fcd2:
     jobs:
     - build-common-layers
-    - windows_amd64_package:
+    - linux_amd64_package:
         requires:
         - build-common-layers
     - bundle-releases:
         requires:
-        - windows_amd64_package
+        - linux_amd64_package
   ci:
     jobs:
     - build
