ci: integrate with packagespec ci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,22 +1,368 @@
-version: 2.1
-orbs:
-  slack: circleci/slack@3.4.2
+### ***
+### WARNING: DO NOT manually EDIT or MERGE this file, it is generated by 'make ci-config'.
+### INSTEAD: Edit or merge the source in config/ then run 'make ci-config'.
+### ***
+# Orb 'circleci/slack@3.4.2' resolved to 'circleci/slack@3.4.2'
+version: 2
 jobs:
+  cache-builder-images:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    steps:
+    - setup_remote_docker:
+        version: 19.03.12
+    - checkout
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        keys:
+        - cache001-copy-source_0f2f_{{checksum ".buildcache/cache-keys/copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5"}}
+        - cache001-download-modules_b298_{{checksum ".buildcache/cache-keys/download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62"}}
+        - cache001-install-deps_2d16_{{checksum ".buildcache/cache-keys/install-deps-2d16c6b83793b47aad77bb2e6ebb2ff70b64c1e9"}}
+    - run:
+        command: |
+          if [ -f .buildcache/archives/02-copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5.tar.gz ]; then
+            echo "Exact match found in cache, skipping build."
+            circleci-agent step halt
+          else
+            echo "No exact match found, proceeding with build."
+          fi
+        name: Finish early if loaded exact match from cache.
+    - run:
+        command: |
+          LAYER_SPEC_ID=02-copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5 make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: make -f packages*.lock/layer.mk 00-install-deps-2d16c6b83793b47aad77bb2e6ebb2ff70b64c1e9-image
+    - run:
+        command: make -f packages*.lock/layer.mk 01-download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62-image
+    - run:
+        command: make -f packages*.lock/layer.mk 02-copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5-image
+    - run:
+        command: make -f packages*.lock/layer.mk 02-copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5-save
+    - save_cache:
+        key: cache001-copy-source_0f2f_{{checksum ".buildcache/cache-keys/copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5"}}
+        paths:
+        - .buildcache/archives/02-copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5.tar.gz
+    - run:
+        command: mv .buildcache/archives/02-copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5.tar.gz .buildcache/archives/01-download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62.tar.gz
+    - save_cache:
+        key: cache001-download-modules_b298_{{checksum ".buildcache/cache-keys/download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62"}}
+        paths:
+        - .buildcache/archives/01-download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62.tar.gz
+    - run:
+        command: mv .buildcache/archives/01-download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62.tar.gz .buildcache/archives/00-install-deps-2d16c6b83793b47aad77bb2e6ebb2ff70b64c1e9.tar.gz
+    - save_cache:
+        key: cache001-install-deps_2d16_{{checksum ".buildcache/cache-keys/install-deps-2d16c6b83793b47aad77bb2e6ebb2ff70b64c1e9"}}
+        paths:
+        - .buildcache/archives/00-install-deps-2d16c6b83793b47aad77bb2e6ebb2ff70b64c1e9.tar.gz
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - PRODUCT_REVISION: ''
+  darwin_amd64_package:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - PRODUCT_REVISION: ''
+    - PACKAGE_SPEC_ID: 6c6c1ed6a95bf40cd3440ca629be711e52983cd1
+    steps:
+    - setup_remote_docker:
+        version: 19.03.12
+    - checkout
+    - run:
+        command: make -C packages*.lock write-package-cache-key
+        name: Write package cache key
+    - restore_cache:
+        key: cache001-package-6c6c1ed6a95bf40cd3440ca629be711e52983cd1-{{checksum ".buildcache/cache-keys/package-6c6c1ed6a95bf40cd3440ca629be711e52983cd1"}}
+    - run:
+        command: |
+          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+            echo "No package found, continuing with build."
+            exit 0
+          fi
+          echo "Package already cached, skipping build."
+          circleci-agent step halt
+        name: Check the cache status.
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        keys:
+        - cache001-copy-source_0f2f_{{checksum ".buildcache/cache-keys/copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5"}}
+        - cache001-download-modules_b298_{{checksum ".buildcache/cache-keys/download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62"}}
+        - cache001-install-deps_2d16_{{checksum ".buildcache/cache-keys/install-deps-2d16c6b83793b47aad77bb2e6ebb2ff70b64c1e9"}}
+    - run:
+        command: |
+          make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: make -C packages*.lock package
+    - run:
+        command: ls -lahR .buildcache/packages
+    - save_cache:
+        key: cache001-package-6c6c1ed6a95bf40cd3440ca629be711e52983cd1-{{checksum ".buildcache/cache-keys/package-6c6c1ed6a95bf40cd3440ca629be711e52983cd1"}}
+        paths:
+        - .buildcache/packages/store
+  linux_amd64_package:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - PRODUCT_REVISION: ''
+    - PACKAGE_SPEC_ID: 69eebe797eef586c6713cc32c1ad0186a5268f51
+    steps:
+    - setup_remote_docker:
+        version: 19.03.12
+    - checkout
+    - run:
+        command: make -C packages*.lock write-package-cache-key
+        name: Write package cache key
+    - restore_cache:
+        key: cache001-package-69eebe797eef586c6713cc32c1ad0186a5268f51-{{checksum ".buildcache/cache-keys/package-69eebe797eef586c6713cc32c1ad0186a5268f51"}}
+    - run:
+        command: |
+          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+            echo "No package found, continuing with build."
+            exit 0
+          fi
+          echo "Package already cached, skipping build."
+          circleci-agent step halt
+        name: Check the cache status.
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        keys:
+        - cache001-copy-source_0f2f_{{checksum ".buildcache/cache-keys/copy-source-0f2f67537f81b566bf36ede6b6d539dacf74a2a5"}}
+        - cache001-download-modules_b298_{{checksum ".buildcache/cache-keys/download-modules-b298c74274cbe268d6b4c7826a0dd425f3138e62"}}
+        - cache001-install-deps_2d16_{{checksum ".buildcache/cache-keys/install-deps-2d16c6b83793b47aad77bb2e6ebb2ff70b64c1e9"}}
+    - run:
+        command: |
+          make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: make -C packages*.lock package
+    - run:
+        command: ls -lahR .buildcache/packages
+    - save_cache:
+        key: cache001-package-69eebe797eef586c6713cc32c1ad0186a5268f51-{{checksum ".buildcache/cache-keys/package-69eebe797eef586c6713cc32c1ad0186a5268f51"}}
+        paths:
+        - .buildcache/packages/store
+  bundle-releases:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    steps:
+    - checkout
+    - run:
+        command: make -C packages*.lock write-all-package-cache-keys
+        name: Write package cache key
+    - restore_cache:
+        key: cache001-package-6c6c1ed6a95bf40cd3440ca629be711e52983cd1-{{checksum ".buildcache/cache-keys/package-6c6c1ed6a95bf40cd3440ca629be711e52983cd1"}}
+    - run:
+        command: |
+          make package-meta
+        environment:
+          PACKAGE_SPEC_ID: 6c6c1ed6a95bf40cd3440ca629be711e52983cd1
+        name: Write package metadata for darwin_amd64_package
+    - restore_cache:
+        key: cache001-package-69eebe797eef586c6713cc32c1ad0186a5268f51-{{checksum ".buildcache/cache-keys/package-69eebe797eef586c6713cc32c1ad0186a5268f51"}}
+    - run:
+        command: |
+          make package-meta
+        environment:
+          PACKAGE_SPEC_ID: 69eebe797eef586c6713cc32c1ad0186a5268f51
+        name: Write package metadata for linux_amd64_package
+    - run:
+        command: make aliases
+        name: Write package aliases
+    - run:
+        command: ls -lahR .buildcache
+        name: List Build Cache
+    - run:
+        command: cp packages*.lock/pkgs.yml lockfile-standalone.yml
+    - store_artifacts:
+        destination: lockfile-standalone.yml
+        path: lockfile-standalone.yml
+    - store_artifacts:
+        destination: packages-standalone
+        path: .buildcache/packages
+    - run:
+        command: tar -czf packages-standalone.tar.gz .buildcache/packages lockfile-standalone.yml
+    - store_artifacts:
+        destination: packages-standalone.tar.gz
+        path: packages-standalone.tar.gz
+    - run:
+        command: tar -czf meta-standalone.tar.gz .buildcache/packages/store/*.json lockfile-standalone.yml
+    - store_artifacts:
+        destination: meta-standalone.tar.gz
+        path: meta-standalone.tar.gz
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - PRODUCT_REVISION: ''
   build:
     machine:
-      image: 'ubuntu-1604:201903-01'
-    working_directory: ~/boundary
+      image: ubuntu-1604:201903-01
     steps:
     - add_ssh_keys:
         fingerprints:
-        # hashicorp-ci github "machine" user, for private modules
-          - "c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98"
+        - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
     - checkout
     - run:
-        name: "Run Acceptance Tests"
         command: |
           make test-ci
-    - slack/status:
-        fail_only: true
-        only_for_branches: master
-        webhook: webhook
+        name: Run Acceptance Tests
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="fail"' >> $BASH_ENV
+        name: Slack - Setting Failure Condition
+        when: on_fail
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="success"' >> $BASH_ENV
+        name: Slack - Setting Success Condition
+        when: on_success
+    - run:
+        command: |
+          if [ ! -x /bin/bash ]; then
+            echo Bash not installed.
+            exit 1
+          fi
+        name: Provide error if non-bash shell
+    - run:
+        command: |
+          current_branch_in_filter=false
+
+          IFS="," read -ra BRANCH_FILTERS <<< "master"
+
+          for i in "${BRANCH_FILTERS[@]}"; do
+            if [ "${i}" == "${CIRCLE_BRANCH}" ]; then
+              current_branch_in_filter=true
+            fi
+          done
+
+          if [ "x" == "xmaster" ] || [ "$current_branch_in_filter" = true ]; then
+            # Provide error if no webhook is set and error. Otherwise continue
+            if [ -z "webhook" ]; then
+              echo "NO SLACK WEBHOOK SET"
+              echo "Please input your SLACK_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
+              exit 1
+            else
+              #Create Members string
+              if [ -n "" ]; then
+                IFS="," read -ra SLACK_MEMBERS <<< ""
+                for i in "${SLACK_MEMBERS[@]}"; do
+                  if [ $(echo ${i} | head -c 1) == "S" ]; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!subteam^${i}> "
+                  elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!${i}> "
+                  else
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<@${i}> "
+                  fi
+                done
+              fi
+              #If successful
+              if [ "$SLACK_BUILD_STATUS" = "success" ]; then
+                #Skip if fail_only
+                if [ true = true ]; then
+                  echo "The job completed successfully"
+                  echo '"fail_only" is set to "true". No Slack notification sent.'
+                else
+                  curl -X POST -H 'Content-type: application/json' \
+                    --data "{ \
+                              \"attachments\": [ \
+                                { \
+                                  \"fallback\": \":tada: A $CIRCLE_JOB job has succeeded!\", \
+                                  \"text\": \":tada: A $CIRCLE_JOB job has succeeded! $SLACK_MENTIONS\", \
+                                  \"fields\": [ \
+                                    { \
+                                      \"title\": \"Project\", \
+                                      \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                                      \"short\": true \
+                                    }, \
+                                    { \
+                                      \"title\": \"Job Number\", \
+                                      \"value\": \"$CIRCLE_BUILD_NUM\", \
+                                      \"short\": true \
+                                    } \
+                                  ], \
+                                  \"actions\": [ \
+                                    { \
+                                      \"type\": \"button\", \
+                                      \"text\": \"Visit Job\", \
+                                      \"url\": \"$CIRCLE_BUILD_URL\" \
+                                    } \
+                                  ], \
+                                  \"color\": \"#1CBF43\" \
+                                } \
+                              ] \
+                            } " webhook
+                  echo "Job completed successfully. Alert sent."
+                fi
+              else
+                #If Failed
+                curl -X POST -H 'Content-type: application/json' \
+                  --data "{ \
+                    \"attachments\": [ \
+                      { \
+                        \"fallback\": \":red_circle: A $CIRCLE_JOB job has failed!\", \
+                        \"text\": \":red_circle: A $CIRCLE_JOB job has failed! $SLACK_MENTIONS\", \
+                        \"fields\": [ \
+                          { \
+                            \"title\": \"Project\", \
+                            \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                            \"short\": true \
+                          }, \
+                          { \
+                            \"title\": \"Job Number\", \
+                            \"value\": \"$CIRCLE_BUILD_NUM\", \
+                            \"short\": true \
+                          } \
+                        ], \
+                        \"actions\": [ \
+                          { \
+                            \"type\": \"button\", \
+                            \"text\": \"Visit Job\", \
+                            \"url\": \"$CIRCLE_BUILD_URL\" \
+                          } \
+                        ], \
+                        \"color\": \"#ed5c5c\" \
+                      } \
+                    ] \
+                  } " webhook
+                echo "Job failed. Alert sent."
+              fi
+            fi
+          else
+            echo "Current branch is not included in only_for_branches filter; no status alert will be sent"
+          fi
+        name: Slack - Sending Status Alert
+        shell: /bin/bash
+        when: always
+    working_directory: ~/boundary
+workflows:
+  build-standalone:
+    jobs:
+    - cache-builder-images
+    - darwin_amd64_package:
+        requires:
+        - cache-builder-images
+    - linux_amd64_package:
+        requires:
+        - cache-builder-images
+    - bundle-releases:
+        requires:
+        - darwin_amd64_package
+        - linux_amd64_package
+  default:
+    jobs:
+    - build
+  version: 2
