add windows + freebsd + set version

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -147,7 +147,7 @@ jobs:
     - AUTO_INSTALL_TOOLS: 'YES'
     - BUILDKIT_PROGRESS: plain
     - PRODUCT_REVISION: ''
-    - PACKAGE_SPEC_ID: a0ba97d1f6d539dc949e65f4f0859e8823062c37
+    - PACKAGE_SPEC_ID: e743b041278cec53847ec7028ebadc3ad5669de2
     steps:
     - setup_remote_docker:
         version: 19.03.12
@@ -159,7 +159,7 @@ jobs:
         command: make -C packages*.lock write-package-cache-key
         name: Write package cache key
     - restore_cache:
-        key: cache006-package-a0ba97d1f6d539dc949e65f4f0859e8823062c37-{{checksum ".buildcache/cache-keys/package-a0ba97d1f6d539dc949e65f4f0859e8823062c37"}}
+        key: cache006-package-e743b041278cec53847ec7028ebadc3ad5669de2-{{checksum ".buildcache/cache-keys/package-e743b041278cec53847ec7028ebadc3ad5669de2"}}
         name: Restore package cache
     - run:
         command: |
@@ -205,7 +205,7 @@ jobs:
         command: ls -lahR .buildcache/packages
         name: List packages
     - save_cache:
-        key: cache006-package-a0ba97d1f6d539dc949e65f4f0859e8823062c37-{{checksum ".buildcache/cache-keys/package-a0ba97d1f6d539dc949e65f4f0859e8823062c37"}}
+        key: cache006-package-e743b041278cec53847ec7028ebadc3ad5669de2-{{checksum ".buildcache/cache-keys/package-e743b041278cec53847ec7028ebadc3ad5669de2"}}
         name: Saving package cache
         paths:
         - .buildcache/packages/store
@@ -217,7 +217,7 @@ jobs:
     - AUTO_INSTALL_TOOLS: 'YES'
     - BUILDKIT_PROGRESS: plain
     - PRODUCT_REVISION: ''
-    - PACKAGE_SPEC_ID: 556901dfda0ede9e6e44f06371985480234f7b8f
+    - PACKAGE_SPEC_ID: 4f1bfeb2a667fafd083e3110d6ee2a714360a71a
     steps:
     - setup_remote_docker:
         version: 19.03.12
@@ -229,7 +229,7 @@ jobs:
         command: make -C packages*.lock write-package-cache-key
         name: Write package cache key
     - restore_cache:
-        key: cache006-package-556901dfda0ede9e6e44f06371985480234f7b8f-{{checksum ".buildcache/cache-keys/package-556901dfda0ede9e6e44f06371985480234f7b8f"}}
+        key: cache006-package-4f1bfeb2a667fafd083e3110d6ee2a714360a71a-{{checksum ".buildcache/cache-keys/package-4f1bfeb2a667fafd083e3110d6ee2a714360a71a"}}
         name: Restore package cache
     - run:
         command: |
@@ -275,7 +275,147 @@ jobs:
         command: ls -lahR .buildcache/packages
         name: List packages
     - save_cache:
-        key: cache006-package-556901dfda0ede9e6e44f06371985480234f7b8f-{{checksum ".buildcache/cache-keys/package-556901dfda0ede9e6e44f06371985480234f7b8f"}}
+        key: cache006-package-4f1bfeb2a667fafd083e3110d6ee2a714360a71a-{{checksum ".buildcache/cache-keys/package-4f1bfeb2a667fafd083e3110d6ee2a714360a71a"}}
+        name: Saving package cache
+        paths:
+        - .buildcache/packages/store
+  windows_amd64_package:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - BUILDKIT_PROGRESS: plain
+    - PRODUCT_REVISION: ''
+    - PACKAGE_SPEC_ID: 2a15eca7152565d54650450b74e49f13fa3aa635
+    steps:
+    - setup_remote_docker:
+        version: 19.03.12
+    - add_ssh_keys:
+        fingerprints:
+        - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
+    - checkout
+    - run:
+        command: make -C packages*.lock write-package-cache-key
+        name: Write package cache key
+    - restore_cache:
+        key: cache006-package-2a15eca7152565d54650450b74e49f13fa3aa635-{{checksum ".buildcache/cache-keys/package-2a15eca7152565d54650450b74e49f13fa3aa635"}}
+        name: Restore package cache
+    - run:
+        command: |
+          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+            echo "No package found, continuing with build."
+            exit 0
+          fi
+          echo "Package already cached, skipping build."
+          circleci-agent step halt
+        name: Check the cache status.
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        keys:
+        - cache006-copy-source_2bf2_{{checksum ".buildcache/cache-keys/copy-source-2bf23f8820c7f77d69c67cc1e898d73e3d002cc9"}}
+        - cache006-go-modules_694e_{{checksum ".buildcache/cache-keys/go-modules-694e8500194e3b187b35bd9a40229f3bd215710e"}}
+        - cache006-ui_5f82_{{checksum ".buildcache/cache-keys/ui-5f82d1f0cbf979ee051aa1ba0f7105483fa6947d"}}
+        - cache006-base_aac1_{{checksum ".buildcache/cache-keys/base-aac1d959b4b3af1495941602b5e51fb6181baded"}}
+        name: Restore build layer cache
+    - run:
+        command: |
+          make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: |2
+
+          KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
+          eval "$(ssh-agent -s)"
+          if [ -f "$KEYFILE" ]; then
+            ssh-add "$KEYFILE"
+          else
+            echo "==> INFO: SSH key for github.com not found"
+            echo "    Attempts to access private repositories from within"
+            echo "    the build will fail, e.g. for private go modules, or"
+            echo "    attempts to directly clone private repositories."
+          fi
+
+          make -C packages*.lock package
+        name: Compile Package
+    - run:
+        command: ls -lahR .buildcache/packages
+        name: List packages
+    - save_cache:
+        key: cache006-package-2a15eca7152565d54650450b74e49f13fa3aa635-{{checksum ".buildcache/cache-keys/package-2a15eca7152565d54650450b74e49f13fa3aa635"}}
+        name: Saving package cache
+        paths:
+        - .buildcache/packages/store
+  freebsd_amd64_package:
+    docker:
+    - image: circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - BUILDKIT_PROGRESS: plain
+    - PRODUCT_REVISION: ''
+    - PACKAGE_SPEC_ID: a39b6fcb6a55e71b7a72b2631cff69c1e4943323
+    steps:
+    - setup_remote_docker:
+        version: 19.03.12
+    - add_ssh_keys:
+        fingerprints:
+        - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
+    - checkout
+    - run:
+        command: make -C packages*.lock write-package-cache-key
+        name: Write package cache key
+    - restore_cache:
+        key: cache006-package-a39b6fcb6a55e71b7a72b2631cff69c1e4943323-{{checksum ".buildcache/cache-keys/package-a39b6fcb6a55e71b7a72b2631cff69c1e4943323"}}
+        name: Restore package cache
+    - run:
+        command: |
+          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+            echo "No package found, continuing with build."
+            exit 0
+          fi
+          echo "Package already cached, skipping build."
+          circleci-agent step halt
+        name: Check the cache status.
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        keys:
+        - cache006-copy-source_2bf2_{{checksum ".buildcache/cache-keys/copy-source-2bf23f8820c7f77d69c67cc1e898d73e3d002cc9"}}
+        - cache006-go-modules_694e_{{checksum ".buildcache/cache-keys/go-modules-694e8500194e3b187b35bd9a40229f3bd215710e"}}
+        - cache006-ui_5f82_{{checksum ".buildcache/cache-keys/ui-5f82d1f0cbf979ee051aa1ba0f7105483fa6947d"}}
+        - cache006-base_aac1_{{checksum ".buildcache/cache-keys/base-aac1d959b4b3af1495941602b5e51fb6181baded"}}
+        name: Restore build layer cache
+    - run:
+        command: |
+          make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: |2
+
+          KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
+          eval "$(ssh-agent -s)"
+          if [ -f "$KEYFILE" ]; then
+            ssh-add "$KEYFILE"
+          else
+            echo "==> INFO: SSH key for github.com not found"
+            echo "    Attempts to access private repositories from within"
+            echo "    the build will fail, e.g. for private go modules, or"
+            echo "    attempts to directly clone private repositories."
+          fi
+
+          make -C packages*.lock package
+        name: Compile Package
+    - run:
+        command: ls -lahR .buildcache/packages
+        name: List packages
+    - save_cache:
+        key: cache006-package-a39b6fcb6a55e71b7a72b2631cff69c1e4943323-{{checksum ".buildcache/cache-keys/package-a39b6fcb6a55e71b7a72b2631cff69c1e4943323"}}
         name: Saving package cache
         paths:
         - .buildcache/packages/store
@@ -289,21 +429,37 @@ jobs:
         command: make -C packages*.lock write-all-package-cache-keys
         name: Write all package cache keys
     - restore_cache:
-        key: cache006-package-a0ba97d1f6d539dc949e65f4f0859e8823062c37-{{checksum ".buildcache/cache-keys/package-a0ba97d1f6d539dc949e65f4f0859e8823062c37"}}
+        key: cache006-package-e743b041278cec53847ec7028ebadc3ad5669de2-{{checksum ".buildcache/cache-keys/package-e743b041278cec53847ec7028ebadc3ad5669de2"}}
     - run:
         command: |
           make package-meta
         environment:
-          PACKAGE_SPEC_ID: a0ba97d1f6d539dc949e65f4f0859e8823062c37
+          PACKAGE_SPEC_ID: e743b041278cec53847ec7028ebadc3ad5669de2
         name: Write package metadata for darwin_amd64_package
     - restore_cache:
-        key: cache006-package-556901dfda0ede9e6e44f06371985480234f7b8f-{{checksum ".buildcache/cache-keys/package-556901dfda0ede9e6e44f06371985480234f7b8f"}}
+        key: cache006-package-4f1bfeb2a667fafd083e3110d6ee2a714360a71a-{{checksum ".buildcache/cache-keys/package-4f1bfeb2a667fafd083e3110d6ee2a714360a71a"}}
     - run:
         command: |
           make package-meta
         environment:
-          PACKAGE_SPEC_ID: 556901dfda0ede9e6e44f06371985480234f7b8f
+          PACKAGE_SPEC_ID: 4f1bfeb2a667fafd083e3110d6ee2a714360a71a
         name: Write package metadata for linux_amd64_package
+    - restore_cache:
+        key: cache006-package-2a15eca7152565d54650450b74e49f13fa3aa635-{{checksum ".buildcache/cache-keys/package-2a15eca7152565d54650450b74e49f13fa3aa635"}}
+    - run:
+        command: |
+          make package-meta
+        environment:
+          PACKAGE_SPEC_ID: 2a15eca7152565d54650450b74e49f13fa3aa635
+        name: Write package metadata for windows_amd64_package
+    - restore_cache:
+        key: cache006-package-a39b6fcb6a55e71b7a72b2631cff69c1e4943323-{{checksum ".buildcache/cache-keys/package-a39b6fcb6a55e71b7a72b2631cff69c1e4943323"}}
+    - run:
+        command: |
+          make package-meta
+        environment:
+          PACKAGE_SPEC_ID: a39b6fcb6a55e71b7a72b2631cff69c1e4943323
+        name: Write package metadata for freebsd_amd64_package
     - run:
         command: make aliases
         name: Write package aliases
@@ -482,10 +638,18 @@ workflows:
     - linux_amd64_package:
         requires:
         - build-common-layers
+    - windows_amd64_package:
+        requires:
+        - build-common-layers
+    - freebsd_amd64_package:
+        requires:
+        - build-common-layers
     - bundle-releases:
         requires:
         - darwin_amd64_package
         - linux_amd64_package
+        - windows_amd64_package
+        - freebsd_amd64_package
   default:
     jobs:
     - build
