CR: Put back retry

diff --git a/.github/workflows/enos-run.yml b/.github/workflows/enos-run.yml
--- a/.github/workflows/enos-run.yml
+++ b/.github/workflows/enos-run.yml
@@ -137,6 +137,8 @@ jobs:
           enos scenario exec --chdir ./enos ${{ matrix.filter }} --cmd "version"
       - name: Run Enos scenario
         id: run
+        # Continue once and retry
+        continue-on-error: true
         env:
           ENOS_VAR_aws_region: us-east-1
           ENOS_VAR_aws_ssh_keypair_name: enos-ci-ssh-key
@@ -157,8 +159,22 @@ jobs:
           retention-days: 5
       - name: Set Enos Job Status
         id: enos-status
-        if: ${{ failure() }}
-        run: echo "status=${{ steps.run.outcome }}" >> $GITHUB_OUTPUT
+        if: ${{ steps.run.outcome == 'failure' || failure() }}
+        run: echo "status=failure" >> $GITHUB_OUTPUT
+      - name: Retry Enos scenario
+        id: run_retry
+        if: steps.run.outcome == 'failure'
+        env:
+          ENOS_VAR_aws_region: us-east-1
+          ENOS_VAR_aws_ssh_keypair_name: enos-ci-ssh-key
+          ENOS_VAR_aws_ssh_private_key_path: ./support/private_key.pem
+          ENOS_VAR_local_boundary_dir: ./support/
+          ENOS_VAR_crt_bundle_path: ./support/boundary.zip
+          ENOS_VAR_tfc_api_token: ${{ secrets.TF_API_TOKEN }}
+          ENOS_VAR_test_email: ${{ secrets.SERVICE_USER_EMAIL }}
+        run: |
+          export ENOS_VAR_enos_user=$GITHUB_ACTOR && \
+          enos scenario run --timeout 60m0s --chdir ./enos ${{ matrix.filter }}
       - name: Destroy Enos scenario
         env:
           ENOS_VAR_aws_region: us-east-1
@@ -176,6 +192,7 @@ jobs:
         run: |
           env
           find ./enos -name "scenario.tf" -exec cat {} \;
+
   notify:
     name: Notify
     needs: enos
